'use client';
import React, { useEffect, useState } from 'react';
interface Project { id:string; category:'shorts'|'commercials'|'prompts'; title:string; subtitle:string; videoSrc:string; aspectRatio:'horizontal'|'vertical'; engine:string; prompt:string; concept:string; role:string; pipeline:string; seed:string; grading:string; }
const projectsData: Record<string, Project> = {
'cyber-noir': { id:'cyber-noir',category:'shorts',title:'《新潮汐 / NEOTIDE》',subtitle:'AIGC 电影质感科幻短片 - AI电影节最佳叙事大奖作品',videoSrc:'/works/work-01-preview.mp4',aspectRatio:'horizontal',engine:'// SYSTEM: RUNWAY-GEN-3_ANAMORPHIC_LENS',prompt:'A wide anamorphic shot...',concept:'《新潮汐》是一部探索AI幻觉、后数字文明末日的实验短片。',role:'AI Video Director / Editor / Sound Design',pipeline:'Midjourney V6 + Runway Gen-3 + DaVinci',seed:'33092817293',grading:'Neo-noir Cyan and Decaying Amber'},
'matrix-dream': { id:'matrix-dream',category:'prompts',title:'《母体纠缠 / MATRIX ENTANGLEMENT》',subtitle:'基于超级变量与负向调度的多维视觉框架体系',videoSrc:'/works/work-03-preview.mp4',aspectRatio:'horizontal',engine:'// SYSTEM: LATENT-RECURSIVE_PROMPT_FLOW',prompt:'A high-contrast cinematic scan...',concept:'本系统展示了 AIGC 的控图边界。',role:'Lead Prompt Architect',pipeline:'Midjourney Matrix Blueprinting',seed:'998412039',grading:'Terminal Green & Monochromatic Shadows'},
'dust-odyssey': { id:'dust-odyssey',category:'shorts',title:'《尘埃奥德赛 / DUST ODYSSEY》',subtitle:'写实废土风格叙事镜头 - 探索微观尘埃粒子动力学',videoSrc:'/works/work-01-preview.mp4',aspectRatio:'horizontal',engine:'// SYSTEM: SORA-PARTICLE_SIMULATION_V2',prompt:'Earthy dramatic anamorphic medium shot...',concept:'《尘埃奥德赛》重点在于对重力物理学和微观悬浮物质的AI算法控制。',role:'Director / Visual Lead',pipeline:'Midjourney + Sora + Stable Diffusion Lora',seed:'10928374921',grading:'Muted Earthy Ochre & Deep Amber'},
'synthetic-dawn': { id:'synthetic-dawn',category:'prompts',title:'《合成黎明 / SYNTHETIC DAWN》',subtitle:'多模态时序融合框架 - 模拟极端自然气候与工业共生',videoSrc:'/works/work-03-preview.mp4',aspectRatio:'horizontal',engine:'// SYSTEM: COGNITIVE-FLOW_WEATHER_EMULATOR',prompt:'Extreme cinematic wide shot...',concept:'此框架深入探讨了在时序生成模型中对气象学剧烈运动的干预。',role:'Technical Prompt Director',pipeline:'Midjourney V6 + Runway Gen-3 + DaVinci Resolve',seed:'44820193872',grading:'Electric Turquoise & Liquid Silver'},
'gold-liquid': { id:'gold-liquid',category:'commercials',title:'《液态重力 / LIQUID GRAVITY》',subtitle:'X-LUXURY 品牌 AI 概念广告特辑',videoSrc:'/works/work-02-preview.mp4',aspectRatio:'vertical',engine:'// SYSTEM: MIDJOURNEY-V6_PHYSICS_GRADING',prompt:'Hyper-abstract luxury dynamic liquid gold...',concept:'此项目是为知名奢侈品牌定制的 9:16 竖屏全案概念广告。',role:'AIGC Art Director / Keyframe Designer',pipeline:'Stable Diffusion + MJ V6 + Kling AI',seed:'5561029418',grading:'Warm Champagne Gold & Pitch Black'},
'analog-rust': { id:'analog-rust',category:'shorts',title:'《旧磁铁与荒野 / ANALOG RUST》',subtitle:'35mm 模拟怀旧电影短片先导视觉',videoSrc:'/works/work-04-preview.mp4',aspectRatio:'vertical',engine:'// SYSTEM: SORA-COHESION_TEST_PROTOTYPE',prompt:'Earthy cinematic portrait shot...',concept:'《旧磁铁与荒野》通过 AIGC 的生成，逆向探索上世纪70年代胶片的杂质感和光学缺陷。',role:'Director / Editor',pipeline:'Sora Beta + Luma Dream Machine',seed:'197410293',grading:'Faded Kodachrome Film emulation'},
'neon-pulse': { id:'neon-pulse',category:'commercials',title:'《霓虹脉冲 / NEON PULSE》',subtitle:'时尚先锋垂直视感广告 - 情感算法流动视觉',videoSrc:'/works/work-02-preview.mp4',aspectRatio:'vertical',engine:'// SYSTEM: COGNITIVE-FLOW_PORTRAIT_STREAM',prompt:'A fast-paced vertical portrait...',concept:'本作品深入探讨时尚媒介的移动化。',role:'Visual Director / Stylist',pipeline:'SDXL ControlNet + Runway Gen-3',seed:'88390129381',grading:'Vibrant Acid Magenta & Deep Onyx'},
};
export default function WorkSection(){const [activeCategory,setActiveCategory]=useState<string>('all'); const [selectedProject,setSelectedProject]=useState<Project|null>(null); useEffect(()=>{document.body.style.overflow=selectedProject?'hidden':''; return ()=>{document.body.style.overflow='';};},[selectedProject]); const filtered=Object.values(projectsData).filter((p)=>activeCategory==='all'||p.category===activeCategory); return <section id="work" className="mx-auto mt-12 w-full max-w-7xl rounded-[38px] border border-white/10 bg-[#090909] px-6 py-12 md:px-10"><p className="text-xs font-mono tracking-[0.3em] text-[#E5A93B] uppercase">AIGC STUDIO</p><h2 className="mt-4 text-3xl font-black tracking-tight text-white uppercase md:text-5xl">作品目录</h2><div className="mt-6 flex flex-wrap gap-3 text-xs font-mono">{['all','shorts','commercials','prompts'].map((k)=><button key={k} onClick={()=>setActiveCategory(k)} className={`rounded-full border px-4 py-2 uppercase ${activeCategory===k?'border-[#E5A93B]/50 text-white':'border-white/20 text-gray-300'}`}>{k}</button>)}</div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((project)=><article key={project.id} onClick={()=>setSelectedProject(project)} className="group cursor-pointer overflow-hidden rounded-2xl border border-white/10 bg-black/50"><div className={`relative ${project.aspectRatio==='vertical'?'aspect-[9/16]':'aspect-video'} bg-[#111]`}><video src={project.videoSrc} autoPlay muted loop playsInline className="h-full w-full object-cover opacity-80 transition group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/></div><div className="p-4"><h3 className="text-lg font-bold text-white">{project.title}</h3><p className="mt-1 text-xs text-gray-400">{project.subtitle}</p></div></article>)}</div>{selectedProject&&<div className="fixed inset-0 z-50 bg-black/90 p-6 backdrop-blur-xl" onClick={()=>setSelectedProject(null)}><div className="mx-auto mt-16 max-w-5xl rounded-2xl border border-white/10 bg-[#0b0b0b] p-6" onClick={(e)=>e.stopPropagation()}><button className="mb-4 text-xs text-gray-400" onClick={()=>setSelectedProject(null)}>CLOSE</button><video src={selectedProject.videoSrc} autoPlay muted loop playsInline className="mb-6 w-full rounded-xl"/><h3 className="text-3xl font-black text-white">{selectedProject.title}</h3><p className="mt-2 text-gray-300">{selectedProject.subtitle}</p><p className="mt-4 text-sm text-gray-400">{selectedProject.concept}</p></div></div>}</section>;}
